<!DOCTYPE html>
<html>
    <head>
        <title><?php echo $this->viewData->appTitle; ?></title>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="<?php echo $this->viewData->metaData->companyName . " | " . $this->viewData->metaData->authorName; ?>" />
        <meta name="keywords" content="<?php echo $this->viewData->metaData->keywords; ?>" />
        <meta name="description" content="<?php echo $this->viewData->metaData->description; ?>" />
    </head>
    <body>
        <view />
    </body>
</html>
